### PR TITLE
feat: added rating

### PR DESCRIPTION
**Pull request by ajit-sharmaGH**
image

### CODE REVIEW

**Review by Omkar-Chaskar — APPROVED** [review]
looks good to merge

**Comment by ajit-sharmaGH** [comment]
> looks good to merge

Thank you!

**Review by munjalSaksham71 — APPROVED** [review]
Everything looks good- You can merge it.

**Comment by ajit-sharmaGH** [comment]
> Everything looks good- You can merge it.

Thank you @munjalSaksham71

**Pull request merged**
